---
title: "KL_loop_angleMeans"
author: "Jake Reed"
date: "`r Sys.Date()`"
output: html_document
---

# Setup up knitr environment
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = getwd())

cat('
<style type="text/css">
b, strong {color: red; }
i, em {color: blue; }
.defn {color: purple; }
.para {color: purple;
      font-weight: bold;
}
.figure { text-align: center; }
.caption { font-weight: bold; }
</style>
')
```

# Import libraries
```{r, results = 'hide'}
library(Seurat)
library(dplyr)
library(Rtsne)
library(TDA)
source(file = file.path(getwd(), 'functions/angleMean2.R'))
source(file = file.path(getwd(), 'functions/comp_ds.R'))
```

# Create directories and load data
```{r, results='hide'}
# Create directories
data_dir <- file.path(getwd(), 'data')
results_dir <- file.path(getwd(), 'results')
if (!file.exists(results_dir)) dir.create(results_dir)

#Don't do this: #setwd(results_dir)

dirLoop <- file.path(results_dir, 'Loop')
if (!file.exists(dirLoop)) dir.create(dirLoop)

# Load test data
load(file = file.path(data_dir, 'seurat_classify.rds'))

```

# Normalize and scale the seurat data
```{r}
# Prepocess data
seurat <- NormalizeData(object = seurat)
seurat <- ScaleData(object = seurat)
```

# Generate angleMeans for each gene then create pie charts from those results
```{r}
gene.ls <- c("FOXP3", "CTLA4", "IKZF2", "IL2RA", "TNFRSF9")


# Subset data
x <- 'Treg'
tr.seurat <- subset(seurat, subset = most_probable_cell_type == x)
# Transform data
data <- t(as.matrix(tr.seurat@assays$RNA@scale.data))

# Run tsne
set.seed(5364)
usable <- Rtsne(data, check_duplicates = FALSE, pca = FALSE)
usable <- as.data.frame(usable$Y)
rownames(usable) <- rownames(data)
# downsample
usable <- downSample(as.matrix(usable), targetNum = 250)

# Perform persistence analysis
rips <- ripsDiag(usable, 
                 maxdimension = 1, 
                 maxscale = 5, 
                 library="Dionysus", 
                 location=TRUE)
```

```{r FOXP3}
gene <- "FOXP3"
gene.exp <- select(as.data.frame(data), all_of(gene))
usable$gene <- as.vector(gene.exp[rownames(usable),1])
tgt <- getLongCycle(rips)
centroid <- getCentroid(tgt)
angles <- getAngles(usable[, 1:2], centroid)
degrees <- angles * 180/pi
G <- c(usable$gene, usable$gene)
D <- c(degrees, degrees + 360)
lo <- loess(G ~ D, span = 0.25)
ox <- order(lo$x)
plot(D, G)
lines(lo$x[ox], lo$fitted[ox], col = "red", lwd=2)

crackle <- usable$gene - min(usable$gene) + 0.01
probs <- crackle/sum(crackle)
set.seed(44188)
N <- 40000
folderol <- sample(1:length(angles), N, replace = TRUE, prob = probs)
hist(A <- degrees[folderol], breaks = 77, prob = TRUE)
dd <- density(A)
lines(dd, col = "red", lwd = 2)
library(movMF)
xy <- as.matrix(usable[folderol, 1:2])
G <- 6
fit <- lapply(1:G, function(K) {
  movMF(xy, k = K)
})
plot(xy, col = "gray", pch = 16)
for (I in 1:G) points(fit[[I]]$theta, pch = 16, cex = 1.5, col = I)

plot(sapply(fit, function(X) X$L), pch = 16)
aic <- sapply(1:G, function(I) {
  model <- fit[[I]]
  -2*logLik(model) + 4*I
})

bic <- sapply(1:G, function(I) {
  model <- fit[[I]]
  -2*logLik(model) + 3*I*log(N)
})
plot(aic, pch=16)
plot(bic, pch = 16)
```

```{r}
# Create angleMeans list to hold result data frames
angle.ls <- list()
for(gene in gene.ls) {
  # Add back expression data
  gene.exp <- select(as.data.frame(data), all_of(gene))
  usable$gene <- as.vector(gene.exp[rownames(usable),1])

  # compute angleMean and add to result list
  angle.ls[[gene]] <- angleMean(usable[, 1:2], rips)
  
}

# Save results
save(angle.ls, file = file.path(dirLoop, 'angleMeans_combined_result.rds'))

# For loop to create and save piechart
for(gene in gene.ls) {
  
  # Create label and filename for plot
  tlt <- paste('Tregs', gene, 'Expression', 'Sector Plot', collapse = " ")
  fname <- paste('Tregs', gene, 'expression', 'sectorPlot', '.png', collapse = '_')
  
  # Setup Pie chart
  lbls <- angle.ls[[gene]]$UpperBound
  slices <- rep(1/dim(angle.ls[[gene]])[1]*100, dim(angle.ls[[gene]])[1])
  
  # Setup color gradient
  rbPal <- colorRampPalette(c('white', 'blue'))
  colors <- rbPal(20)[cut(angle.ls[[gene]]$Mean, breaks = 20)]

  # Create save destination
  png(file = file.path(dirLoop, paste(fname)),
      width = 1000, height = 1000, bg = "white")
  
  # Plot pie chart
  pie(slices, labels = lbls, col=colors, main = tlt, cex.main = 3, 
      cex = 2)
  
  dev.off()
  
}

```